

// File generated by OpenXava: Fri Jun 15 11:27:37 CEST 2018
// Archivo generado por OpenXava: Fri Jun 15 11:27:37 CEST 2018

// WARNING: NO EDIT
// OJO: NO EDITAR
// Component: Worker		Java interface for entity/Interfaz java para Entidad

package org.openxava.test.model;

import java.math.*;
import java.rmi.RemoteException;


public interface IWorker  extends org.openxava.model.IModel {	

	// Properties/Propiedades 	
	public static final String PROPERTY_id = "id"; 	
	Integer getId() throws RemoteException; 	
	public static final String PROPERTY_hourPrice = "hourPrice"; 
	java.math.BigDecimal getHourPrice() throws RemoteException;
	void setHourPrice(java.math.BigDecimal hourPrice) throws RemoteException; 	
	public static final String PROPERTY_nickName = "nickName"; 
	String getNickName() throws RemoteException;
	void setNickName(String nickName) throws RemoteException; 	
	public static final String PROPERTY_fullName = "fullName"; 
	String getFullName() throws RemoteException;
	void setFullName(String fullName) throws RemoteException;		

	// References/Referencias

	// Methods 


}