/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2021-11-05 14:03:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.naviox;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import org.openxava.application.meta.MetaModule;
import com.openxava.naviox.model.Folder;

public final class modulesList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.openxava.naviox.Modules modules = null;
      synchronized (session) {
        modules = (com.openxava.naviox.Modules) _jspx_page_context.getAttribute("modules", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (modules == null){
          modules = new com.openxava.naviox.Modules();
          _jspx_page_context.setAttribute("modules", modules, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\n');
      com.openxava.naviox.Folders folders = null;
      synchronized (session) {
        folders = (com.openxava.naviox.Folders) _jspx_page_context.getAttribute("folders", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (folders == null){
          folders = new com.openxava.naviox.Folders();
          _jspx_page_context.setAttribute("folders", folders, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write(' ');
      out.write('\n');
      out.write('\n');
 
folders.setModules(modules); 

for (Iterator it= folders.getSubfolders().iterator(); it.hasNext();) {
	Folder folder = (Folder) it.next();

      out.write("\t\n");
      out.write("\t<a  href=\"javascript:naviox.goFolder('");
      out.print(folder.getId());
      out.write("')\">\n");
      out.write("\t<div class=\"folder-row \" >\t\n");
      out.write("\t\t<div class=\"folder-name\">\n");
      out.write("\t\t\t<i class=\"mdi mdi-");
      out.print(folder.getIcon());
      out.write("\"></i>\n");
      out.write("\t\t\t");
      out.print(folder.getLabel());
      out.write("\n");
      out.write("\t\t\t<i class=\"folder-icon mdi mdi-chevron-right\"></i>\n");
      out.write("\t\t</div>\t\t\n");
      out.write("\t</div>\t\n");
      out.write("\t</a>\n");
      out.write("\t\n");
	
}

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "selectModules.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("folderModules", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", request.getCharacterEncoding()), out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
